name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  papi_component:
    strategy:
      matrix:
        component: [perf_event, lmsensors, io, net, powercap, appio, coretemp, stealtime]
        builder: [basic, spack]
      fail-fast: false
    runs-on: cpu_intel
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: .github/workflows/${{matrix.builder}}.sh ${{matrix.component}}
  papi_component_nvidia:
    strategy:
      matrix:
        component: [cuda, nvml]
        builder: [basic, spack]
      fail-fast: false
    runs-on: gpu_nvidia
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: .github/workflows/${{matrix.builder}}.sh ${{matrix.component}}
  papi_component_amd:
    strategy:
      matrix:
        component: [rocm, rocm_smi]
        builder: [basic, spack]
      fail-fast: false
    runs-on: gpu_amd
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: .github/workflows/${{matrix.builder}}.sh ${{matrix.component}}
# powercap_ppc
# sensors_ppc
# infiniband
